-- MySQL Script generated by MySQL Workbench
-- Wed Nov 21 12:43:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Account` (
  `NomeUtente` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Cognome` VARCHAR(45) NOT NULL,
  `DataDiNascita` DATE NOT NULL,
  PRIMARY KEY (`NomeUtente`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC),
  UNIQUE INDEX `NumeroDiTelefono_UNIQUE` (`Cognome` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Populating table `mydb`.`Account`
-- -----------------------------------------------------
INSERT INTO Account
VALUES 
('Sbugheaz', 'Giacop96', 'gianmarco.coppola@community.unipa.it', 'Gianmarco', 'Coppola', '1996-10-19'),
('ElMosca96', 'Giumos96', 'giuseppe.moscarelli96@gmail.com', 'Giuseppe', 'Moscarelli', '1996-06-05'),
('Aries96', 'Andvar96', 'andryplus96@gmail.com', 'Andrea', 'Vara', '1996-06-10');

-- -----------------------------------------------------
-- Table `mydb`.`Amicizia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Amicizia` (
  `Account_NomeUtente` VARCHAR(45) NOT NULL,
  `Account_NomeUtente1` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Account_NomeUtente`, `Account_NomeUtente1`),
  INDEX `fk_Amicizia_Account2_idx` (`Account_NomeUtente1` ASC),
  CONSTRAINT `fk_Amicizia_Account1`
    FOREIGN KEY (`Account_NomeUtente`)
    REFERENCES `mydb`.`Account` (`NomeUtente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Amicizia_Account2`
    FOREIGN KEY (`Account_NomeUtente1`)
    REFERENCES `mydb`.`Account` (`NomeUtente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Brano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Brano` (
  `IDBrano` INT NOT NULL AUTO_INCREMENT,
  `Titolo` VARCHAR(45) NOT NULL,
  `Artista` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDBrano`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Populating table `mydb`.`Brano`
-- -----------------------------------------------------
INSERT INTO Brano
VALUES 
(1, 'Tranne te', 'Fabri Fibra'),
(2, 'Il ballo delle incertezze', 'Ultimo'),
(3, 'TNT', 'ACDC');

-- -----------------------------------------------------
-- Table `mydb`.`Playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Playlist` (
  `IDPlaylist` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `NumeroBrani` INT NOT NULL,
  `Account_NomeUtente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDPlaylist`),
  UNIQUE INDEX `Nome_UNIQUE` (`Nome` ASC),
  INDEX `fk_Playlist_Account_idx` (`Account_NomeUtente` ASC),
  CONSTRAINT `fk_Playlist_Account`
    FOREIGN KEY (`Account_NomeUtente`)
    REFERENCES `mydb`.`Account` (`NomeUtente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Populating table `mydb`.`Playlist`
-- -----------------------------------------------------
INSERT INTO Playlist
VALUES 
(1, 'Classico', 10, 'ElMosca96');

-- -----------------------------------------------------
-- Table `mydb`.`Composizione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Composizione` (
  `Playlist_IDPlaylist` INT NOT NULL,
  `OrdineBrano` INT NOT NULL,
  `Brano_IDBrano` INT NOT NULL,
  PRIMARY KEY (`OrdineBrano`, `Playlist_IDPlaylist`),
  INDEX `fk_Composizione_Playlist1_idx` (`Playlist_IDPlaylist` ASC),
  INDEX `fk_Composizione_Brano1_idx` (`Brano_IDBrano` ASC),
  CONSTRAINT `fk_Composizione_Playlist1`
    FOREIGN KEY (`Playlist_IDPlaylist`)
    REFERENCES `mydb`.`Playlist` (`IDPlaylist`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Composizione_Brano1`
    FOREIGN KEY (`Brano_IDBrano`)
    REFERENCES `mydb`.`Brano` (`IDBrano`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Populating table `mydb`.`Composizione`
-- -----------------------------------------------------
INSERT INTO Composizione
VALUES 
(1, 1, 1),
(1, 2, 2),
(1, 3, 3);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
