-- MySQL Script generated by MySQL Workbench
-- Sun Dec  2 22:09:22 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Account` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Account` (
  `NomeUtente` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Cognome` VARCHAR(45) NOT NULL,
  `DataDiNascita` DATE NOT NULL,
  `Attivazione` BIT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`NomeUtente`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC),
  UNIQUE INDEX `NumeroDiTelefono_UNIQUE` (`Cognome` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Populating table `mydb`.`Account`
-- -----------------------------------------------------
INSERT INTO Account
VALUES 
('Sbugheaz', 'Giacop96', 'gianmarco.coppola@community.unipa.it', 'Gianmarco', 'Coppola', '1996-10-19', '1'),
('ElMosca96', 'Giumos96', 'giuseppe.moscarelli96@gmail.com', 'Giuseppe', 'Moscarelli', '1996-06-05', '1'),
('Aries96', 'Andvar96', 'andryplus96@gmail.com', 'Andrea', 'Vara', '1996-06-10', '0');


-- -----------------------------------------------------
-- Table `mydb`.`Amicizia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Amicizia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Amicizia` (
  `Ref1_NomeUtente` VARCHAR(45) NOT NULL,
  `Ref2_NomeUtente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Ref1_NomeUtente`, `Ref2_NomeUtente`),
  INDEX `fk_Amicizia_Account2_idx` (`Ref2_NomeUtente` ASC),
  CONSTRAINT `fk_Amicizia_Account1`
    FOREIGN KEY (`Ref1_NomeUtente`)
    REFERENCES `mydb`.`Account` (`NomeUtente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Amicizia_Account2`
    FOREIGN KEY (`Ref2_NomeUtente`)
    REFERENCES `mydb`.`Account` (`NomeUtente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Populating table `mydb`.`Amicizia`
-- -----------------------------------------------------
INSERT INTO Amicizia
VALUES 
('Sbugheaz', 'ElMosca96');


-- -----------------------------------------------------
-- Table `mydb`.`Brano`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Brano` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Brano` (
  `IDBrano` INT NOT NULL AUTO_INCREMENT,
  `Titolo` VARCHAR(45) NOT NULL,
  `Artista` VARCHAR(45) NOT NULL,
  `Genere` VARCHAR(45) NOT NULL,
  `Anno` DATE NOT NULL,
  `Durata` INT UNSIGNED NOT NULL,
  `Url_cover` VARCHAR(150) NOT NULL DEFAULT '/media/cover/default-brano.png',
  `Url_brano` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDBrano`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Composizione`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Composizione` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Composizione` (
  `OrdineBrano` INT NOT NULL,
  `Ref_IDPlaylist` INT NOT NULL,
  `Ref_IDBrano` INT NOT NULL,
  PRIMARY KEY (`OrdineBrano`, `Ref_IDPlaylist`),
  INDEX `fk_Composizione_Playlist1_idx` (`Ref_IDPlaylist` ASC),
  INDEX `fk_Composizione_Brano1_idx` (`Ref_IDBrano` ASC),
  CONSTRAINT `fk_Composizione_Playlist1`
    FOREIGN KEY (`Ref_IDPlaylist`)
    REFERENCES `mydb`.`Playlist` (`IDPlaylist`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Composizione_Brano1`
    FOREIGN KEY (`Ref_IDBrano`)
    REFERENCES `mydb`.`Brano` (`IDBrano`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Playlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Playlist` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Playlist` (
  `IDPlaylist` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `NumeroBrani` INT NOT NULL,
  PRIMARY KEY (`IDPlaylist`),
  UNIQUE INDEX `Nome_UNIQUE` (`Nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Possiede`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Possiede` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Possiede` (
  `Ref_NomeUtente` VARCHAR(45) NOT NULL,
  `Ref_IDPlaylist` INT NOT NULL,
  PRIMARY KEY (`Ref_NomeUtente`, `Ref_IDPlaylist`),
  INDEX `fk_Possiede_Playlist1_idx` (`Ref_IDPlaylist` ASC),
  CONSTRAINT `fk_Possiede_Account1`
    FOREIGN KEY (`Ref_NomeUtente`)
    REFERENCES `mydb`.`Account` (`NomeUtente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Possiede_Playlist1`
    FOREIGN KEY (`Ref_IDPlaylist`)
    REFERENCES `mydb`.`Playlist` (`IDPlaylist`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
